Data cleaning

Data scaling

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("/content/Data Cleaning_part1_dataset_movie scores.csv")
df

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
1        NaN       NaN   NaN    NaN              NaN               NaN
2      Stark      Mike  48.0      m              NaN               NaN
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [ ]:
df[(df['pre_movie_score'].isnull()) & df['Gender'].notnull()]

  first_name last_name   age Gender  pre_movie_score  post_movie_score
2      Stark      Mike  48.0      m              NaN               NaN

In [ ]:
df

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
1        NaN       NaN   NaN    NaN              NaN               NaN
2      Stark      Mike  48.0      m              NaN               NaN
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [ ]:
df.isna().sum().sum()

8

In [ ]:
df

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
1        NaN       NaN   NaN    NaN              NaN               NaN
2      Stark      Mike  48.0      m              NaN               NaN
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [ ]:
df1=df.dropna(axis=0)

In [ ]:
df

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
1        NaN       NaN   NaN    NaN              NaN               NaN
2      Stark      Mike  48.0      m              NaN               NaN
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [ ]:
df1

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [ ]:
df1.isna().sum().sum()

0

In [ ]:
df2=df.dropna(axis=1)

In [ ]:
df2

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [ ]:
df2.isna().sum().sum()

0.0

In [ ]:
df4=df.dropna(thresh=2)

In [ ]:
df4

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
2      Stark      Mike  48.0      m              NaN               NaN
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [ ]:
df

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
1        NaN       NaN   NaN    NaN              NaN               NaN
2      Stark      Mike  48.0      m              NaN               NaN
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [ ]:
df5=df.dropna(thresh=1,axis=1)

In [ ]:
df5

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
1        NaN       NaN   NaN    NaN              NaN               NaN
2      Stark      Mike  48.0      m              NaN               NaN
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [ ]:
df.fillna("NEW")

  first_name last_name   age Gender pre_movie_score post_movie_score
0       Root      Joss  36.0      m             8.0              9.0
1        NEW       NEW   NEW    NEW             NEW              NEW
2      Stark      Mike  48.0      m             NEW              NEW
3      Sofie    Miller  39.0      f             7.0              8.0
4       Emma       Roy  84.0      f             6.0              8.0

In [ ]:
df['age']

0    36.0
1     NaN
2    48.0
3    39.0
4    84.0
Name: age, dtype: float64

In [ ]:
df['age'].fillna(5)

0    36.0
1     5.0
2    48.0
3    39.0
4    84.0
Name: age, dtype: float64

In [ ]:
df['first_name']

0     Root
1      NaN
2    Stark
3    Sofie
4     Emma
Name: first_name, dtype: object

In [ ]:
df['first_name'] = df['first_name'].fillna("Empty")

In [ ]:
df

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
1      Empty       NaN   NaN    NaN              NaN               NaN
2      Stark      Mike  48.0      m              NaN               NaN
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [ ]:
df['Gender'] = df['Gender'].fillna("m")

In [ ]:
df

  first_name last_name   age Gender  pre_movie_score  post_movie_score
0       Root      Joss  36.0      m              8.0               9.0
1      Empty       NaN   NaN      m              NaN               NaN
2      Stark      Mike  48.0      m              NaN               NaN
3      Sofie    Miller  39.0      f              7.0               8.0
4       Emma       Roy  84.0      f              6.0               8.0

In [ ]:
df['post_movie_score']

0    9.0
1    NaN
2    NaN
3    8.0
4    8.0
Name: post_movie_score, dtype: float64

In [ ]:
df['pre_movie_score'].mean()

7.0

In [ ]:
df['pre_movie_score'].fillna(df['pre_movie_score'].mean())

0    8.0
1    7.0
2    7.0
3    7.0
4    6.0
Name: pre_movie_score, dtype: float64

In [ ]:
df['age']

0    36.0
1     NaN
2    48.0
3    39.0
4    84.0
Name: age, dtype: float64

In [ ]:
df['age'].fillna(df['age'].mean()).round()

0    36.0
1    52.0
2    48.0
3    39.0
4    84.0
Name: age, dtype: float64

In [ ]:
dz=pd.read_csv("/content/Data Cleaning_part1_dataset_Students_expenses.csv")

In [ ]:
dz

   Expenses  Riya  Samual   Neeti  Shreya
0   January  8100  6200.0  9200.0  8150.0
1  February  9500  7500.0     NaN  7200.0
2     March  7300  6100.0  8800.0  8100.0
3     April  7800  7200.0  8900.0  7500.0
4       May  8500     NaN  9100.0  7800.0
5      June  9200  7100.0  8850.0     NaN

In [ ]:
dz.mean()

<ipython-input-51-b9c5241c73b5>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  dz.mean()

Riya      8400.0
Samual    6820.0
Neeti     8970.0
Shreya    7750.0
dtype: float64

In [ ]:
dz[(dz['Expenses'].isnull()) & dz['Shreya'].notnull()]

Empty DataFrame
Columns: [Expenses, Riya, Samual, Neeti, Shreya]
Index: []

In [ ]:
dz.isna().sum()

Expenses    0
Riya        0
Samual      1
Neeti       1
Shreya      1
dtype: int64

In [ ]:
dz.isna().sum().sum()

3

In [ ]:
dz.fillna(dz.mean())

<ipython-input-52-82e594575398>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  dz.fillna(dz.mean())

   Expenses  Riya  Samual   Neeti  Shreya
0   January  8100  6200.0  9200.0  8150.0
1  February  9500  7500.0  8970.0  7200.0
2     March  7300  6100.0  8800.0  8100.0
3     April  7800  7200.0  8900.0  7500.0
4       May  8500  6820.0  9100.0  7800.0
5      June  9200  7100.0  8850.0  7750.0

In [ ]:
dz.median()

<ipython-input-53-98d6a6046c6f>:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  dz.median()

Riya      8300.0
Samual    7100.0
Neeti     8900.0
Shreya    7800.0
dtype: float64

In [ ]:
dz.fillna(dz.median())

<ipython-input-54-990a3f9ae3fa>:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  dz.fillna(dz.median())

   Expenses  Riya  Samual   Neeti  Shreya
0   January  8100  6200.0  9200.0  8150.0
1  February  9500  7500.0  8900.0  7200.0
2     March  7300  6100.0  8800.0  8100.0
3     April  7800  7200.0  8900.0  7500.0
4       May  8500  7100.0  9100.0  7800.0
5      June  9200  7100.0  8850.0  7800.0